apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ostad-capstone-production
  namespace: argocd
  labels:
    app: ostad-capstone
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    repoURL: https://github.com/mdarifahammedreza/Ostad-Capstone-project.git
    targetRevision: main
    path: k8s/production
    
  destination:
    server: https://kubernetes.default.svc
    namespace: ostad-production
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
  revisionHistoryLimit: 10
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    
  info:
  - name: 'Description'
    value: 'Ostad Capstone Project - Production Deployment'
  - name: 'Owner'
    value: 'Md Arif Ahammedrez'
  - name: 'LinkedIn'
    value: 'https://www.linkedin.com/in/mdarifahammedreza/'
